[env:mimxrt1060_evk]
platform = platformio/nxpimxrt
board = mimxrt1060_evk
framework =

build_flags =
    -mcpu=cortex-m7
    -mthumb
    -mfpu=fpv5-d16
    -mfloat-abi=hard
    -DCPU_MIMXRT1062DVL6A
    -DFREEARDU_BARE_METAL
    -O3
    -ffunction-sections
    -fdata-sections
    -fno-exceptions
    -fno-rtti
    -nostartfiles
    -Wl,--gc-sections
    -Wl,--entry=reset_handler
    -Wl,-T,imxrt1060.ld

build_src_filter =
    +<*>

upload_protocol = jlink
debug_tool = jlink