[platformio]
src_dir = FreeARDU\src
include_dir = FreeARDU\include
test_dir = FreeARDU\test

[env:mimxrt1060_evk]
platform = platformio/nxpimxrt
board = mimxrt1060_evk
framework =

build_flags =
    -Wl,-T,FreeARDU/imxrt1060.ld
    -Wl,--nostdlib
    -mcpu=cortex-m7
    -mthumb
    -mfpu=fpv5-d16
    -mfloat-abi=soft
    -DCPU_MIMXRT1062DVL6A
    -DFREEARDU_BARE_METAL
    -O3
    -ffunction-sections
    -fdata-sections
    -fno-exceptions
    -fno-rtti
    -nostartfiles
    -Wl,--gc-sections
    -Wl,--relax

build_src_filter =
    +<*.c>
    +<*.cpp>
    +<*.S>
    +<*/*.c>
    +<*/*.cpp>
    +<*/*.S>
    +<*/*/*.c>
    +<*/*/*.cpp>
    +<*/*/*.S>
    +<*/*/*/*.c>
    +<*/*/*/*.cpp>
    +<*/*/*/*.S>

[env:mimxrt1060_evk_release]
platform = platformio/nxpimxrt
board = mimxrt1060_evk
framework =

build_flags =
    -Wl,-T,FreeARDU/imxrt1060.ld
    -Wl,--nostdlib
    -mcpu=cortex-m7
    -mthumb
    -mfpu=fpv5-d16
    -mfloat-abi=soft
    -DCPU_MIMXRT1062DVL6A
    -DFREEARDU_BARE_METAL
    -O3
    -ffunction-sections
    -fdata-sections
    -fno-exceptions
    -fno-rtti
    -nostartfiles
    -DNDEBUG
    -Wl,--gc-sections
    -Wl,--relax

build_src_filter =
    +<*.c>
    +<*.cpp>
    +<*.S>
    +<*/*.c>
    +<*/*.cpp>
    +<*/*.S>
    +<*/*/*.c>
    +<*/*/*.cpp>
    +<*/*/*.S>
    +<*/*/*/*.c>
    +<*/*/*/*.cpp>
    +<*/*/*/*.S>

upload_protocol = jlink
debug_tool = jlink